# Generated by Django 6.0.6 on 2026-06-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('signs_of_damage', models.TextField()),
                ('prevention', models.TextField()),
                ('crop_health', models.IntegerField()),
                ('yield_loss', models.IntegerField()),
            ],
        ),
    ]
