# Generated by Django 6.0.6 on 2026-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseinfo',
            name='recommendation',
            field=models.TextField(default='Recommendation not available.'),
            preserve_default=False,
        ),
    ]
